#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: marcoonroad's blog
title: marcoonroad's blog

# Short bio or description (displayed in the header)
description: Zzzzzz...

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/75941_684038581685637_5336390958017503811_n.jpg?efg=eyJpIjoiYiJ9&oh=86f594ae941da4319af9356b76552d14&oe=589DEB67
avatar: https://avatars3.githubusercontent.com/u/3820407?s=460&v=4

github-projects:
  - hieroglyphs
  - sporadic
  - nocoiner
  - spadille
  - twostep

github-projects-descriptions:
  - name: modest
    description: "Script/module mode detection while running/loading Lua files."
  - name: families
    description: "Concatenation-based prototypes implementation for Lua."
  - name: talents
    description: "Pluggable contextual talents implementation for Lua."
  - name: cuid
    description: "CUID generator for Lua."
  - name: hieroglyphs
    description: "Quantum-resistant, purely Hash-based, Stateful, One-Time Digital Signatures for OCaml."
  - name: sporadic
    description: "Composable Concurrency Abstractions for JavaScript."
  - name: nocoiner
    description: "A Commitment Scheme library for Coin Flipping/Tossing algorithms and sort."
  - name: spadille
    description: "Verifiable/deterministic fair tickets generation for lotteries, raffles and gambling games."
  - name: twostep
    description: "HOTP and TOTP algorithms for 2-step verification (for OCaml)."

personal-resumes:
  - path: docs/resume.pdf
    label: "Resume EN-US"
  - path: docs/curriculo.pdf
    label: "Currículo PT-BR"
  - path: docs/cover-letter.pdf
    label: "Cover Letter EN-US"
  - path: docs/carta-de-apresentacao.pdf
    label: "Carta Apres. PT-BR"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: marcoonroad@gmail.com
  facebook: # marcoonroad
  flickr:
  github: marcoonroad # barryclark/jekyll-now
  instagram: marcoonroad
  spotify: "https://open.spotify.com/user/31p6jaavqahpv6sloy2xdc7re6mi?si=iSQzkS9SShG9hAfFnFh51Q" # whole URL here
  youtubemusic: "https://music.youtube.com/playlist?list=PLd79hgAAAf3hI8rXrX0t0_LVqw4fzjQbF" # whole URL here too
  linkedin: marcoonroad
  pinterest: marcoonroad
  rss: feed # just type anything here for a working RSS icon
  twitter: marcoonroad
  stackoverflow: "users/4379818/marco-aurélio-da-silva"
  youtube: user/marcoonroad7
  googleplus: # anything in your profile username that comes after plus.google.com/
  # ethereum: "0x74Bd7803A3e3bA7d28baf5aD22287D0506A04b67"
  # bitcoin: "13jnVxMenKUWb1RA1pKsQkri5HY1u89o2D"
  # tezos: "tz1Y5yUPjqkc32EwpfGFmCbqNCXm7253Csu9"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: marcoonroad

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-41209773-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://marcoonroad.dev"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.7.4

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag
  - jemoji
# - jekyll-press

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
